#!/bin/bash

# System Information
HOSTNAME=$(hostname)
#cat-cat command use to concatenate files
#grep-grep command is used to set data line for matching files and patterns
#cut-The cut command is used to remove particular columns from a file
OS=$(cat /etc/os-release | grep PRETTY_NAME | cut -d '=' -f 2 | tr -d '"')
UPTIME=$(uptime -p)

# Hardware Information
CPU=$(lscpu | grep "Model name" | awk -F ': ' '{print $2}')
#awk-To print particular columns from a file awk command is used
RAM=$(free -h | awk '/^Mem:/ {print $2}')
DISKS=$(lsblk -io NAME,TYPE,SIZE | grep "disk" | awk '{print $1 ": " $3}')
VIDEO=$(lspci | grep -i 'VGA\|3D\|2D' | awk '{$1=""; print $0}')

# Network Information
FQDN=$(hostname -f)
HOST_IP=$(hostname -I | awk '{print $1}')
GATEWAY_IP=$(ip route | awk '/default/ {print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}')
INTERFACE=$(ip -o link show | awk -F': ' '{print $2}')
IP_CIDR=$(ip -o addr show | awk '{print $4}')

# System Status
#sort-used to sort lines of text files in alphabetically
USERS=$(who | awk '{print $1}' | sort -u | tr '\n' ',')
DISK_SPACE=$(df -h --output=source,avail | grep "^/" | awk '{print $1 ": " $2}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(uptime | grep -o "load average: .*" | awk '{print $3,$4,$5}')
MEMORY=$(free -h | grep Mem | awk '{print $3}')
LISTEN_PORTS=$(ss -tuln | awk 'NR > 1 {print $5}' | cut -d: -f2 | sort -u | tr '\n' ',')
UFW_RULES=$(sudo ufw status numbered | grep -v "^Status:")

# Output the system report
echo "System Report generated by $(whoami), $(date +%Y-%m-%d\ %H:%M:%S)"
echo
echo "System Information"
echo "------------------"
echo "Hostname: $HOSTNAME"
echo "OS: $OS"
echo "Uptime: $UPTIME"
echo
echo "Hardware Information"
echo "--------------------"
echo "CPU: $CPU"
echo "RAM: $RAM"
echo "Disks: $DISKS"
echo "Video: $VIDEO"
echo
echo "Network Information"
echo "-------------------"
echo "FQDN: $FQDN"
echo "Host Address: $HOST_IP"
echo "Gateway IP: $GATEWAY_IP"
echo "DNS Server: $DNS_SERVER"
echo "Interface Name: $INTERFACE"
echo "IP Address: $IP_CIDR"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: ${USERS::-1}"
echo "Disk Space: $DISK_SPACE"
echo "Process Count: $PROCESS_COUNT"
echo "Load Averages: $LOAD_AVERAGES"
echo "Memory Allocation: $MEMORY"
echo "Listening Network Ports: ${LISTEN_PORTS::-1}"
echo "UFW Rules: $UFW_RULES"
